### ISSUE TITLE
Uploading Browning student list...

### ISSUE THREAD

**Issue by BBHLF** [scottag99/myhomelibrary#88]
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

It looks like the bulk upload format has changed to add external_id.  Skipped ID field with grade and the upload was successful.

**Comment by scottag99** [comment]
Can you attach the file you uploaded that caused the error?

**Comment by BBHLF** [comment]
[Browning Summer 2017 MHL Campaign List.xlsx](https://github.com/scottag99/myhomelibrary/files/890217/Browning.Summer.2017.MHL.Campaign.List.xlsx)
Though we external_id in creating history of transactions, I have some concern that some schools may not be able to share student ID.  I was able to successfully upload the attached file by removing the external_id column.
