### ISSUE TITLE
Checkout Price Change Issue...

### ISSUE THREAD

**Issue by BBHLF** [scottag99/myhomelibrary#95]
Users can successfully change the calculated donation prior to SUBMIT/Checkout.  I.e. A donor R. Cummins on 4/25 added 15 wish list to the cart and changed the donation total to $30 before checkout.  All 15 wish list IDs are visible on the Kimbia report.  Unsure if the workflows labels these wish lists as fully sponsors.

**Comment by scottag99** [comment]
The amount is not spread out amongst the selected wish lists, which is wrong. So presently, yes, it would show as sponsored. I'm working on a bug fix for this now.
