### ISSUE TITLE
Report of sponsored wish lists showing as Sponsor Wish List...

### ISSUE THREAD

**Issue by BBHLF** [scottag99/myhomelibrary#96]
A Treasure Forest teacher has recruited donors to sponsor every child in her class.  Donors/Teacher are reporting that students who have been sponsored are still showing up in searches and the button at the bottom of their wish list reads Sponsor Wish List.

Can this button have three phases:  Sponsor Wish List; Added to Cart; Sponsored?

**Comment by scottag99** [comment]
Would it be possible to get an example of students they believed to be sponsored?

**Comment by BBHLF** [comment]
I asked the Principal and Teacher for some sample names that might be reappearing for sponsorship.  Will forward as soon as they reply.

Sincerely,
José Paulo Calvillo, Director of Operations
Barbara Bush Houston Literacy Foundation
7887 San Felipe, Suite 250
Houston, TX 77063
(346) 212-2310<tel:%28346%29%20212-2310> Office
(713) 460-4058<tel:%28713%29%20460-4058> Cell
[cid:BRHSWzqhD5PB]BushHoustonLiteracy<http://www.facebook.com/BushHoustonLiteracy>

[cid:557b34a920ef4]<http://www.bushhoustonliteracy.org/>
